version: '3'
services:
  my-app:
    image: #image from the private repository here. This step is shown on Step 6.
      ports: 3004:3001
  nginx:
    image: nginx
    ports:
     - 3010:80
  # mongodb:
    # image: mongo
    # ports: 
    #  - 27017:37017
    # enviroment:
    #  - MONGO-INITDB_ROOT_USERNAME=admin
    #  - MONGO-INITDB_ROOT_USERNAME=password
    # volumes:
    #  - mongo-data:/data/db
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #    - 8080:8080
  #   environment:
  #    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #    - ME_CONFIG_MONGODB_ADMINPASSWORD= password
  #    - ME_CONFIG_MONGODB_SERVER=mongodb   



#  -p 3010:80
#  --name nginxTest
#  --net test-Network
#  nginx
